---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on: [push]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install Ruby dependencies
        uses: ruby/setup-ruby@v1
        with:
<<<<<<< HEAD
          ruby-version: 3.2.2
=======
<<<<<<< HEAD
<<<<<<< HEAD
          ruby-version: 3.2.2
=======
          ruby-version: 2.7.8
>>>>>>> a0b0a9d (commit)
=======
          ruby-version: 2.7.8
>>>>>>> a0b0a9d (commit)
>>>>>>> e75e6a3 (commit)
          bundler-cache: true

      - name: Install Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm install --production

      - name: Build site
        run: bundle exec jekyll build

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4.0.2
        env:
          DEFAULT_BRANCH: main
<<<<<<< HEAD
          FILTER_REGEX_INCLUDE: .*(\assets|\_pages|\_site).*
=======
<<<<<<< HEAD
<<<<<<< HEAD
          FILTER_REGEX_INCLUDE: .*(\assets|\_pages|\_site).*
=======
          FILTER_REGEX_INCLUDE: .*(\_assets|\_pages|\_site).*
>>>>>>> a0b0a9d (commit)
=======
          FILTER_REGEX_INCLUDE: .*(\_assets|\_pages|\_site).*
>>>>>>> a0b0a9d (commit)
>>>>>>> e75e6a3 (commit)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_MARKDOWN: true
